import { test, expect } from '@playwright/test';
function pdfFixture() {
  const objects = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R 5 0 R 7 0 R] /Count 3 >>'];
  for (let i = 0; i < 3; i++) {
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 9 0 R >> >> /Contents ${4 + i * 2} 0 R >>`);
    const stream = `BT /F1 24 Tf 72 700 Td (Reading test page ${i + 1}) Tj ET`;
    objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
  }
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  let pdf = '%PDF-1.4\n', offsets = [0];
  for (let i = 0; i < objects.length; i++) { offsets.push(pdf.length); pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`; }
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n` + offsets.slice(1).map(n => `${String(n).padStart(10, '0')} 00000 n \n`).join('');
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf);
}
test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('librarian.installDismissed', '1'));
});
test('import, render, bookmark, resume offline, export and organize a PDF', async ({ page, context }, info) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await page.locator('[data-import]').first().setInputFiles({ name: 'Reading sample.pdf', mimeType: 'application/pdf', buffer: pdfFixture() });
  await expect(page.locator('.pdf-card')).toHaveCount(1);
  await page.locator('.pdf-actions [data-read]').click();
  await expect(page.locator('.pdf-page').first()).toBeVisible();
  await page.locator('[data-page-number]').fill('2');
  await page.locator('[data-page-form] button').click();
  await expect(page.locator('[data-page-number]')).toHaveValue('2');
  await page.locator('[data-bookmark-page]').click();
  await expect(page.locator('[data-bookmark-page]')).toHaveAttribute('aria-pressed', 'true');
  await page.locator('[data-reader-close]').click();
  await expect(page.locator('.continue-reading')).toContainText('Page 2 of 3');
  await page.reload();
  await expect(page.locator('.pdf-card')).toHaveCount(1);
  // Bundled app assets remain available, as they do on capacitor://localhost.
  await page.route('https://**', route => route.abort());
  await page.locator('.pdf-actions [data-read]').click();
  await expect(page.locator('[data-page-number]')).toHaveValue('2');
  await expect(page.locator('.pdf-page').first()).toBeVisible();
  await expect(page.locator('[data-bookmark-page]')).toHaveAttribute('aria-pressed', 'true');
  await page.locator('[data-dark-toggle]').click();
  await expect(page.locator('#pdf-reader')).toHaveAttribute('data-dark', '1');
  await page.screenshot({ path: `test-results/${info.project.name}-reader.png` });
  await page.locator('[data-reader-close]').click();
  await page.unroute('https://**');
  const download = page.waitForEvent('download');
  await page.locator('[data-download-pdf]').click();
  expect((await download).suggestedFilename()).toBe('Reading sample.pdf');
  await page.locator('[data-finished]').click();
  await page.locator('[data-library-filter="finished"]').click();
  await expect(page.locator('.pdf-card')).toHaveCount(1);
  await page.locator('[data-library-filter="unread"]').click();
  await expect(page.locator('.pdf-card')).toHaveCount(0);
  await page.locator('[data-library-filter="all"]').click();
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: "instant" }));
  await page.screenshot({ path: `test-results/${info.project.name}-library.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
test('only licensed exact files can be saved; imported and saved PDFs read offline', async ({ page }, info) => {
  await page.addInitScript(() => localStorage.setItem('librarian.offSources', JSON.stringify(['Open Library', 'Google Books', 'Project Gutenberg / Gutendex', 'Crossref', 'Internet Archive', 'CORE', 'DPLA', 'Europeana', 'K10plus', 'Library of Congress', 'BnF', 'DNB', 'Finna', 'Nasjonalbiblioteket'])));
  const work = { doi: 'https://doi.org/10.1234/book', id: 'https://openalex.org/W123', display_name: 'Licensed book', authorships: [{author:{display_name:'Author'}}], locations: [{is_oa:true, license:'cc-by', version:'publishedVersion', pdf_url:'https://files.example/book.pdf', landing_page_url:'https://publisher.example/book'}] };
  let allowDownload = true;
  await page.route('https://api.crossref.org/**', route => route.fulfill({headers:{'access-control-allow-origin':'*'},json:{message:{DOI:'10.1234/book',license:[{'content-version':'vor',URL:'https://creativecommons.org/licenses/by/4.0/',start:{timestamp:1}}]}}}));
  await page.route('https://api.openalex.org/**', route => route.fulfill({headers:{'access-control-allow-origin':'*'}, json: route.request().url().includes('/works/W123') ? {...work, locations: allowDownload ? work.locations : []} : {results:[work, {id:'https://openalex.org/W456',display_name:'Unlicensed book',open_access:{is_oa:true,oa_url:'https://files.example/unlicensed.pdf'}, locations:[{is_oa:true,license:null,pdf_url:'https://files.example/unlicensed.pdf'}]}]}}));
  let fileRequests = 0;
  await page.route('https://files.example/**', route => { fileRequests++; return route.fulfill({headers:{'access-control-allow-origin':'*'},contentType:'application/pdf',body:pdfFixture()}); });
  await page.goto('/');
  await page.locator('[data-tab="search"]').first().click();
  await page.locator('[data-form] input').fill('book');
  await page.locator('[data-form] button').click();
  await page.locator('[data-select="oa:https://openalex.org/W456"]').click();
  await expect(page.locator('[data-read-result]')).toHaveCount(0);
  await expect(page.getByRole('dialog')).toContainText('confirmed CC0 or CC BY 4.0 license');
  await page.locator('.modal-close').click();
  await page.locator('[data-select="oa:https://openalex.org/W123"]').click();
  await expect(page.locator('[data-read-result]')).toHaveCount(0);
  await page.locator('[data-check-download]').click();
  await expect(page.locator('[data-read-result]')).toBeVisible();
  allowDownload = false;
  await page.locator('[data-save-pdf]').click();
  await expect(page.getByRole('dialog')).toContainText('permission is no longer confirmed');
  expect(fileRequests).toBe(0);
  allowDownload = true;
  await page.locator('[data-read-result]').click();
  await expect(page.locator('.pdf-page').first()).toBeVisible();
  await page.locator('[data-reader-close]').click();
  await page.locator('[data-tab="library"]').click();
  await expect(page.locator('.pdf-card')).toHaveCount(1);
  await expect(page.getByRole('link', {name:'CC BY 4.0 license'})).toHaveAttribute('href','https://creativecommons.org/licenses/by/4.0/');
  await page.screenshot({path:`test-results/${info.project.name}-licensed-library.png`,fullPage:true});
  const shared = page.waitForEvent('download');
  await page.locator('[data-download-pdf]').click();
  await shared;
  await expect(page.getByRole('link',{name:'Save attribution'})).toBeVisible();
  await page.route('https://**', route => route.abort());
  await page.locator('.pdf-actions [data-read]').click();
  await expect(page.locator('.pdf-page').first()).toBeVisible();
});

test('release recovery, privacy, accessibility, and deliberate removal', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('librarian.saved.v1', '{"not":"an array"}');
    localStorage.setItem('librarian.readerZoom', 'NaN');
  });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.locator('[data-tab="privacy"]').click();
  await expect(page.locator('.privacy-copy')).toContainText('Imported PDFs');
  await expect(page.getByRole('link', { name: 'Company privacy policy' })).toHaveAttribute('href', 'https://thecreatingco.com/privacy/');
  await page.locator('[data-tab="library"]').click();
  await page.locator('[data-import]').first().setInputFiles({ name: 'Not a real.pdf', mimeType: 'application/pdf', buffer: Buffer.from('<html>Sign in</html>') });
  await expect(page.getByRole('alert')).toContainText('not a PDF');
  await expect(page.locator('.pdf-card')).toHaveCount(0);
  await page.locator('[data-import]').first().setInputFiles({ name: 'Accessible.pdf', mimeType: 'application/pdf', buffer: pdfFixture() });
  await page.locator('.pdf-actions [data-read]').click();
  await expect(page.locator('.pdf-page').first()).toBeVisible();
  await page.locator('[data-text-mode]').click();
  await expect(page.locator('.text-page')).toContainText('Reading test page 1');
  await page.locator('[data-page-step="1"]').click();
  await expect(page.locator('.text-page')).toContainText('Reading test page 2');
  await page.locator('[data-text-mode]').click();
  await expect(page.locator('.pdf-page').first()).toBeVisible();
  await page.locator('[data-reader-close]').click();
  page.once('dialog', dialog => dialog.dismiss());
  await page.locator('[data-del-pdf]').click();
  await expect(page.locator('.pdf-card')).toHaveCount(1);
  page.once('dialog', dialog => dialog.accept());
  await page.locator('[data-del-pdf]').click();
  await expect(page.locator('.pdf-card')).toHaveCount(0);
  await page.reload();
  await expect(page.locator('.pdf-card')).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
