// Bundled disclosure remains readable without a network connection.
export function privacySection() {
  return `<section class="section"><div class="wrap privacy-copy"><p class="eyebrow">Librarian · Help & privacy</p><h2>Your books stay with you.</h2>
  <h3>Reading and saving</h3><p>Add PDFs from Files or save supported books from Discover. Library holds downloaded content; Shelf holds catalog references. Use Save / Share to export a copy to Files. Removing a book here removes only Librarian’s copy. There is no cloud synchronization; keep exports of important documents. Deleting the app may remove its local library.</p>
  <h3>Privacy on this device</h3><p>Imported PDFs, downloaded books, bookmarks, reading progress, shelf entries and preferences are stored on this device. Importing or reading a saved file does not upload its contents to thecreateco or an AI provider. This release does not offer account sign-in, advertising, tracking, or AI recommendations.</p>
  <h3>When Librarian connects</h3><p>Discover sends your search terms to the enabled catalogs, directly or through our hosted proxy. Catalogs, book hosts and hosting providers receive normal connection information, such as your IP address and requested URL. Covers and fonts may load from external providers. Their retention practices are governed by their own privacy policies. Sources lets you choose which catalogs to search.</p>
  <h3>Your choices</h3><p>You can read downloaded books without an internet connection, remove individual books and shelf entries, and export documents using the system share sheet. Sharing sends the selected copy to the destination you choose. Our support form sends the information you enter to thecreateco; it does not automatically attach your library.</p>
  <h3>Content and accessibility</h3><p>Only download or import content you are entitled to use. Availability and copyright status vary by country and edition. Scanned PDFs without embedded text need OCR in another tool before Text view can read their words. Password-protected PDFs are not supported in this release.</p>
  <p><a href="https://thecreatingco.com/privacy/" target="_blank" rel="noopener noreferrer">Company privacy policy</a> · <a href="https://thecreatingco.com/testing/?category=privacy#feedback" target="_blank" rel="noopener noreferrer">Support & privacy requests</a></p>
  <p class="ai-note">Librarian 1.0 · Updated October 6, 2026. For privacy requests, identify Librarian and the service involved; local files are not available to our support team.</p></div></section>`;
}
